package mp3_player;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

public class MainFrame extends javax.swing.JFrame {

    long total_length;
    long pouse;
    FileInputStream FIS;
    BufferedInputStream BIS;
    Player player;
    
    File myfile=null;
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_play = new javax.swing.JButton();
        btn_pouse = new javax.swing.JButton();
        btn_resume = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btn_play.setText("Play");
        btn_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_playMouseReleased(evt);
            }
        });

        btn_pouse.setText("Pouse");
        btn_pouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_pouseMouseReleased(evt);
            }
        });

        btn_resume.setText("Resume");
        btn_resume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_resumeMouseReleased(evt);
            }
        });

        btn_stop.setText("Stop");
        btn_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_stopMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_play)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pouse)
                        .addGap(18, 18, 18)
                        .addComponent(btn_resume)
                        .addGap(18, 18, 18)
                        .addComponent(btn_stop)
                        .addContainerGap(410, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_play)
                    .addComponent(btn_pouse)
                    .addComponent(btn_resume)
                    .addComponent(btn_stop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playMouseReleased
        JFileChooser chooser=new JFileChooser();
        
        int val=chooser.showOpenDialog(null);
        if(val==JFileChooser.APPROVE_OPTION)
        {
            myfile=chooser.getSelectedFile();
            String song=myfile+"";
            String name=chooser.getSelectedFile().getName();
            jLabel1.setText(name);
        }
        try
        {
            FIS=new FileInputStream(myfile);
            BIS=new BufferedInputStream(FIS);
            player=new Player(BIS);
            total_length=FIS.available();
            new Thread()
            {
                public void run()
                {
                    try
                    {
                        player.play();
                    }
                    catch(JavaLayerException ex)
                    {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
                    }
                }
            }.start();
        }
        catch(IOException ex)
        {
           Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
        }
        catch(JavaLayerException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
        }
        
    }//GEN-LAST:event_btn_playMouseReleased

    private void btn_pouseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pouseMouseReleased
        if(player !=null)
        {
            try
            {
                pouse=FIS.available();
                player.close();
            }
            catch(IOException ex)
            {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
            }
        }


    }//GEN-LAST:event_btn_pouseMouseReleased

    private void btn_resumeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resumeMouseReleased
       try
       {
           FIS=new FileInputStream(myfile);
           BIS=new BufferedInputStream(FIS);
           player=new Player(BIS);
           FIS.skip(total_length-pouse);
           new Thread()
           {
               public void run()
               {
                   try
                   {
                       player.play();
                   }
                   catch(JavaLayerException ex)
                    {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
                    }
               }
           }.start();
       }
       catch(IOException ex)
       {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
       }
       catch(JavaLayerException ex)
        {
           Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btn_resumeMouseReleased

    private void btn_stopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stopMouseReleased
       
        if(player!=null)
        {
            player.close();
            jLabel1.setText(null);
        }
    }//GEN-LAST:event_btn_stopMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_pouse;
    private javax.swing.JButton btn_resume;
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
